# Generated by Django 3.1.7 on 2021-03-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='download.jpg', null=True, upload_to='profile/'),
        ),
    ]
