# Generated by Django 3.1.7 on 2021-03-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20210331_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='download.jpeg', null=True, upload_to='profile/'),
        ),
    ]
